version: '3.4'
  
services:
  mongodb:
    ports:
      - 27017:27017

  order-web:
    build:
      args:
        BUILD_MODE: --prod
        CONFIG_MODE: --configuration=production
    ports:
      - "4200:4200"

  order-api:
    ports:
      - "4000:3000"

  payment-api:
    ports:
      - "3000:3000"
      
